### ISSUE TITLE
Is there an option for how many times retry a failed message? 

### ISSUE THREAD

**Issue by OsmanAktemur** [AllQuietApp/MongoQueueing#1]
It would be great if such a feature existed, but I couldn't see it in the documentation and i think it would be nice if there a field on the document for exception details for a failed message

**Comment by madsquist** [comment]
Currently, that's a fixed value. But it's easy to add. Will create an update tomorrow Berlin Time.

Out of curiosity: what options are you thinking about?

**Comment by madsquist** [comment]
Hey @OsmanAktemur , the latest version 1.2.6 let's you configure the retry intervals:
https://github.com/AllQuietApp/MongoQueueing#queueoptions

**Comment by OsmanAktemur** [comment]
@madsquist thank you, and if these option would be configurable it would very cool

- Display exception details of failed message on seperate field of document
- And lastly not sure but maybe there should be  "retention period configuration" like 7 , 14 days"  (maybe MongoDB TTL index should be useful for this) (not very necessary because it is easy to run delete script to old messages )

**Comment by OsmanAktemur** [comment]
Lastly, I am grateful for writing such a simple tool , it is exactly the solution I was looking for it  for a project that is not complex to require rabbitmq, kafka, etc.  😄

**Comment by madsquist** [comment]
Could you elaborate on "retention period configuration" @OsmanAktemur. There a a few possible options how this could look like, e.g.
Auto removal of message after a) last process or b) after first creation? 

Remember that adding a TTL index requires MongoDB to manage more data and will make the queue theoratically slower because more indexes need to be managed. It probably really depends on if it's "worth" deleting messages.

**Comment by madsquist** [comment]
> @madsquist thank you, and if these option would be configurable it would very cool
> 
>     * Display exception details of failed message on seperate field of document
> 
It's added in version 1.2.7: 
https://github.com/AllQuietApp/MongoQueueing#queueoptions

**Comment by OsmanAktemur** [comment]
> Could you elaborate on "retention period configuration" @OsmanAktemur. There a a few possible options how this could look like, e.g. Auto removal of message after a) last process or b) after first creation?
> 
> Remember that adding a TTL index requires MongoDB to manage more data and will make the queue theoratically slower because more indexes need to be managed. It probably really depends on if it's "worth" deleting messages.

Two options come to my mind;
1- Deleting the message directly instead of marking it as processed (this makes queue faster becaue of small data & index size but lack of ability for replay old messages)
2- Delete only processed messages after "X days" from processed date. (i think existing status + timestamp index will cover this)
   
I think failed or pending messages should not be deleted, should be taken action on them manually.

**Comment by OsmanAktemur** [comment]
But like i said, this delete message option is very optional not must , for now it is easy to set job to delete old messages :) 
This version is very enough for me thank you, above options just suggestion for the project

**Comment by madsquist** [comment]
>1- Deleting the message directly instead of marking it as processed (this makes queue faster becaue of small data & index size but lack of ability for replay old messages) 2- Delete only processed messages after "X days" from processed date. (i think existing status + timestamp index will cover this)

This is a good idea, I'll create a new release with this feature. Thanks @OsmanAktemur

**Comment by madsquist** [comment]
@OsmanAktemur I added `ClearSuccessfulMessages` in version 1.2.8
